export interface SeedCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
}

export interface SeedAuction {
  id: string;
  host_id: string;
  title: string;
  description: string;
  category_id: string;
  image_url: string;
  starting_price: number;
  min_increment: number;
  current_highest_bid: number;
  highest_bidder_id: string | null;
  highest_bidder_name?: string;
  total_bids_count: number;
  unique_bidders_count: number;
  status: "LIVE" | "UPCOMING" | "ENDED";
  subscription_fee: number;
  is_subscription_paid: boolean;
  winner_id?: string | null;
  winning_bid_amount?: number | null;
  settled_at_offset_mins?: number; // negative minutes from now
  start_offset_mins: number; // negative if started in past, positive if upcoming
  duration_mins: number;
  bids?: Array<{
    bidder_id: string;
    amount: number;
    minutesAgo: number;
  }>;
}

export const CATEGORIES_DATA: SeedCategory[] = [
  { id: "cat_watches", name: "Horology & Luxury Watches", slug: "watches", description: "Grand complications, independent chronometers, and vintage Haute Horlogerie." },
  { id: "cat_collectibles", name: "Rare Collectibles & Numismatics", slug: "collectibles", description: "Ancient coins, space mission artifacts, stamps, and royal memorabilia." },
  { id: "cat_tech", name: "Futuristic Tech & Vintage Computing", slug: "tech", description: "Engineering prototypes, first-generation silicon, and historic computing hardware." },
  { id: "cat_art", name: "Masterpieces & Fine Art", slug: "art", description: "Original oil canvases, historic watercolor studies, and verified masterworks." },
  { id: "cat_automotive", name: "Classic Automobiles & Supercars", slug: "automotive", description: "Homologation specials, vintage grand tourers, and legendary racing icons." },
  { id: "cat_cameras", name: "Vintage Cameras & Optics", slug: "cameras", description: "Rangefinders, NASA-spec flight bodies, TLRs, and rare Carl Zeiss optics." },
  { id: "cat_books", name: "Rare Books & Historical Manuscripts", slug: "books", description: "First edition printings, scientific milestones, and hand-illuminated leaves." },
  { id: "cat_jewelry", name: "Antique Jewelry & Rare Gems", slug: "jewelry", description: "Golconda diamonds, royal emeralds, Art Deco platinum, and unheated rubies." },
  { id: "cat_sculptures", name: "Sculptures & Ancient Relics", slug: "sculptures", description: "Chola bronzes, Greco-Roman marble busts, and ancient civilization seals." },
  { id: "cat_memorabilia", name: "Space, Cinema & Sports Memorabilia", slug: "memorabilia", description: "Apollo lunar logs, screen-used film props, and championship game-worn jerseys." },
];

export function generateAllAuctions(): SeedAuction[] {
  const hosts = ["usr_host_ananya", "usr_host_vikram"];
  const buyers = ["usr_buyer_rahul", "usr_buyer_arjun", "usr_buyer_priya"];

  const auctions: SeedAuction[] = [];

  // ============================================================================
  // 1. 42 LIVE AUCTIONS (Running Now with Staggered Endings)
  // ============================================================================

  // Luxury Watches (5 Live)
  auctions.push(
    {
      id: "auc_live_patek",
      host_id: "usr_host_ananya",
      title: "Patek Philippe Grandmaster Chime Ref. 6300G In White Gold",
      description: "Dual-faced reversible wristwatch featuring 20 grand complications including five striking chime modes, acoustic alarm, and instantaneous perpetual calendar. Pristine box, papers, and Geneva archive extract.",
      category_id: "cat_watches",
      image_url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80",
      starting_price: 150000,
      min_increment: 5000,
      current_highest_bid: 185000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 7,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -90,
      duration_mins: 120, // Ends in 30m
      bids: [
        { bidder_id: "usr_buyer_rahul", amount: 155000, minutesAgo: 80 },
        { bidder_id: "usr_buyer_priya", amount: 165000, minutesAgo: 50 },
        { bidder_id: "usr_buyer_arjun", amount: 185000, minutesAgo: 10 },
      ],
    },
    {
      id: "auc_live_rolex_daytona",
      host_id: "usr_host_vikram",
      title: "1968 Rolex Cosmograph Daytona Ref. 6239 'Paul Newman' Dial",
      description: "Legendary exotic tricolor step-dial with art-deco font numerals and Singer manufacturing stamp. Fully documented single-family provenance from Zurich.",
      category_id: "cat_watches",
      image_url: "https://images.unsplash.com/photo-1547996160-71dfabb1a7cf?auto=format&fit=crop&w=1200&q=80",
      starting_price: 250000,
      min_increment: 10000,
      current_highest_bid: 310000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 6,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -45,
      duration_mins: 65, // Ends in 20m
      bids: [
        { bidder_id: "usr_buyer_priya", amount: 270000, minutesAgo: 30 },
        { bidder_id: "usr_buyer_rahul", amount: 310000, minutesAgo: 8 },
      ],
    },
    {
      id: "auc_live_ap_royaloak",
      host_id: "usr_host_ananya",
      title: "Audemars Piguet Royal Oak Concept Flying Tourbillon GMT",
      description: "Sandblasted titanium 44mm architectural case, green ceramic bezel, flying tourbillon at 9 o'clock and dual time-zone selector at 3 o'clock.",
      category_id: "cat_watches",
      image_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
      starting_price: 120000,
      min_increment: 4000,
      current_highest_bid: 144000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 4,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -30,
      duration_mins: 180, // Ends in 150m
    },
    {
      id: "auc_live_lange_zeitwerk",
      host_id: "usr_host_vikram",
      title: "A. Lange & Söhne Zeitwerk Minute Repeater in Platinum",
      description: "The world's only mechanical decimal minute repeater watch with jumping numeral digital displays. Glashütte manufacture caliber L043.5.",
      category_id: "cat_watches",
      image_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80",
      starting_price: 180000,
      min_increment: 5000,
      current_highest_bid: 205000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 5,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -60,
      duration_mins: 240,
    },
    {
      id: "auc_live_rm011",
      host_id: "usr_host_ananya",
      title: "Richard Mille RM 011 Felipe Massa Flyback Chronograph Titanium",
      description: "Skeletonized automatic movement with adjustable rotor geometry, 60-minute countdown timer, and oversized date aperture. Formula 1 race provenance.",
      category_id: "cat_watches",
      image_url: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1200&q=80",
      starting_price: 210000,
      min_increment: 8000,
      current_highest_bid: 242000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 4,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -20,
      duration_mins: 75,
    }
  );

  // Rare Collectibles & Numismatics (5 Live)
  auctions.push(
    {
      id: "auc_live_chandrayaan",
      host_id: "usr_host_vikram",
      title: "ISRO Chandrayaan-3 Propulsion Stage Titanium Alloy Ingot #001",
      description: "Certified flight-hardware surplus titanium grade-5 coupon tested at Sriharikota SHAR test facility. Serial #CY3-PROP-001 with laser etched ISRO emblem.",
      category_id: "cat_collectibles",
      image_url: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80",
      starting_price: 10000,
      min_increment: 500,
      current_highest_bid: 16500,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 11,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -120,
      duration_mins: 135, // Ends in 15m
      bids: [
        { bidder_id: "usr_buyer_arjun", amount: 12000, minutesAgo: 90 },
        { bidder_id: "usr_buyer_priya", amount: 14500, minutesAgo: 40 },
        { bidder_id: "usr_buyer_rahul", amount: 16500, minutesAgo: 5 },
      ],
    },
    {
      id: "auc_live_jahangir_mohur",
      host_id: "usr_host_ananya",
      title: "1605 Mughal Emperor Jahangir Zodiac Gold Mohur (Leo Lion)",
      description: "Struck at Agra mint during AH 1028 (1619 CE). Exquisite depiction of crouching royal lion facing radiant sun. High relief numismatic rarity graded NGC MS-62.",
      category_id: "cat_collectibles",
      image_url: "https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&w=1200&q=80",
      starting_price: 85000,
      min_increment: 3000,
      current_highest_bid: 106000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 8,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -40,
      duration_mins: 160,
    },
    {
      id: "auc_live_flowing_hair",
      host_id: "usr_host_vikram",
      title: "1794 US Flowing Hair Silver Dollar Reproduction Archival Ingot",
      description: "Certified fine bullion museum recreation cast from 3D laser scan of the Smithsonian National Numismatic Collection specimen. Limited to 10 worldwide.",
      category_id: "cat_collectibles",
      image_url: "https://images.unsplash.com/photo-1541480601022-2308c0f02487?auto=format&fit=crop&w=1200&q=80",
      starting_price: 25000,
      min_increment: 1000,
      current_highest_bid: 31000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 5,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -15,
      duration_mins: 180,
    },
    {
      id: "auc_live_east_india_mohur",
      host_id: "usr_host_ananya",
      title: "1835 British East India Company William IV Two Mohurs Gold Proof",
      description: "Calcutta mint specimen with frosted bust of King William IV and reverse depicting radiant lion walking beneath palm tree. Uncirculated NGC PF-63 Cameo.",
      category_id: "cat_collectibles",
      image_url: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1200&q=80",
      starting_price: 95000,
      min_increment: 3500,
      current_highest_bid: 112500,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 6,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -50,
      duration_mins: 110,
    },
    {
      id: "auc_live_victoria_proof",
      host_id: "usr_host_vikram",
      title: "1854 Queen Victoria One Rupee Continuous Legend Proof Pattern",
      description: "Extremely rare proof pattern struck in silver with continuous legend surrounding diademed royal profile. Ex-David Fore collection provenance.",
      category_id: "cat_collectibles",
      image_url: "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=1200&q=80",
      starting_price: 45000,
      min_increment: 1500,
      current_highest_bid: 52500,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 4,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -10,
      duration_mins: 90,
    }
  );

  // Futuristic Tech & Vintage Prototypes (4 Live)
  auctions.push(
    {
      id: "auc_live_cray1_board",
      host_id: "usr_host_ananya",
      title: "1976 Cray-1 Vector Supercomputer Logic Module Board #04",
      description: "Original 8-layer ECL semiconductor logic gate board with freon cooling copper thermal transfer bus bar. Hand-inspected by Seymour Cray.",
      category_id: "cat_tech",
      image_url: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
      starting_price: 35000,
      min_increment: 1500,
      current_highest_bid: 44000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 7,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -80,
      duration_mins: 95, // Ends in 15m
    },
    {
      id: "auc_live_enigma_m4",
      host_id: "usr_host_vikram",
      title: "WWII Kriegsmarine 4-Rotor Enigma M4 Cipher Machine Component",
      description: "Original nickel-plated military entry stator and Steckerbrett patch cord panel from U-Boat naval transmitter. Certified authentic Bletchley Park archival extract.",
      category_id: "cat_tech",
      image_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
      starting_price: 110000,
      min_increment: 4000,
      current_highest_bid: 134000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 5,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -35,
      duration_mins: 140,
    },
    {
      id: "auc_live_apple_newton",
      host_id: "usr_host_ananya",
      title: "Apple Computer 'Cadillac' Prototype Transparent Newton MessagePad",
      description: "Clear acrylic engineering validation test chassis unit built by Apple Cupertino Advanced Technology Group in 1992 before the commercial launch of ARM RISC.",
      category_id: "cat_tech",
      image_url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
      starting_price: 40000,
      min_increment: 2000,
      current_highest_bid: 50000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 6,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -15,
      duration_mins: 120,
    },
    {
      id: "auc_live_walkman_proto",
      host_id: "usr_host_vikram",
      title: "1979 Sony TPS-L2 'Soundabout' Japanese Market Pre-Production Unit",
      description: "Original metallic blue dual-jack stereo cassette player with original MDR-3L2 lightweight orange foam headphones and factory leather carrying pouch.",
      category_id: "cat_tech",
      image_url: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80",
      starting_price: 18000,
      min_increment: 1000,
      current_highest_bid: 23000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 4,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -45,
      duration_mins: 200,
    }
  );

  // Masterpieces & Fine Art (5 Live)
  auctions.push(
    {
      id: "auc_live_raja_ravi_varma",
      host_id: "usr_host_ananya",
      title: "Raja Ravi Varma Original Oil on Canvas 'Damayanti with Royal Hamsa'",
      description: "Magnificent turn-of-the-century oil depicting Princess Damayanti conversing with the golden swan. Retains original carved teakwood frame from Travancore Royal Atelier.",
      category_id: "cat_art",
      image_url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
      starting_price: 450000,
      min_increment: 15000,
      current_highest_bid: 540000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 9,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -110,
      duration_mins: 130, // Ends in 20m
    },
    {
      id: "auc_live_tagore_wash",
      host_id: "usr_host_vikram",
      title: "Rabindranath Tagore 1934 Ink & Colored Wash on Handmade Paper",
      description: "Expressive figurative portrait 'Face of a Mystic' by the Nobel Laureate. Exhibited at Santiniketan Kala Bhavana and accompanied by certificate from the Tagore Foundation.",
      category_id: "cat_art",
      image_url: "https://images.unsplash.com/photo-1578925518470-4def7a0f08bb?auto=format&fit=crop&w=1200&q=80",
      starting_price: 180000,
      min_increment: 5000,
      current_highest_bid: 215000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 6,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -70,
      duration_mins: 220,
    },
    {
      id: "auc_live_husain_horses",
      host_id: "usr_host_ananya",
      title: "M.F. Husain Iconic Acrylic on Canvas 'Lightning Horses of the Sun'",
      description: "Signed monumental horizontal composition depicting three charging steeds against cobalt blue and saffron fields. Provenance: Private collection Mumbai.",
      category_id: "cat_art",
      image_url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80",
      starting_price: 320000,
      min_increment: 10000,
      current_highest_bid: 380000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 7,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -25,
      duration_mins: 150,
    },
    {
      id: "auc_live_amrita_shergil",
      host_id: "usr_host_vikram",
      title: "Amrita Sher-Gil 1937 Oil Study 'Three Young Girls in Village Saree'",
      description: "Intimate figurative composition blending Parisian post-impressionist technique with poignant Indian village life. Verified by the National Gallery of Modern Art trustees.",
      category_id: "cat_art",
      image_url: "https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=1200&q=80",
      starting_price: 500000,
      min_increment: 20000,
      current_highest_bid: 620000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 8,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -50,
      duration_mins: 170,
    },
    {
      id: "auc_live_monet_heliogravure",
      host_id: "usr_host_ananya",
      title: "Claude Monet 1899 Hand-Colored Heliogravure 'Nymphéas au Bassin'",
      description: "Rare proof print overseen by Monet in Giverny and annotated in graphite on heavy Arches watermarked paper. Provenance: Durand-Ruel Gallery, Paris.",
      category_id: "cat_art",
      image_url: "https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1200&q=80",
      starting_price: 140000,
      min_increment: 5000,
      current_highest_bid: 165000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 5,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -15,
      duration_mins: 280,
    }
  );

  // Classic Automobiles & Supercars (5 Live)
  auctions.push(
    {
      id: "auc_live_aston_db5",
      host_id: "usr_host_vikram",
      title: "1964 Aston Martin DB5 Saloon in Silver Birch (Chassis #DB5/1486/R)",
      description: "Matching-numbers 4.0-liter straight-six with triple SU carburetors and ZF 5-speed manual gearbox. Restored by Aston Martin Works with British Motor Industry Heritage Trust certificate.",
      category_id: "cat_automotive",
      image_url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
      starting_price: 750000,
      min_increment: 25000,
      current_highest_bid: 925000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 10,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -100,
      duration_mins: 125, // Ends in 25m
    },
    {
      id: "auc_live_300sl_gullwing",
      host_id: "usr_host_ananya",
      title: "1955 Mercedes-Benz 300 SL Gullwing Coupe in DB 180 Silver Grey",
      description: "Direct mechanical fuel injection 3.0L M198 inline-six engine with original Rudge knock-off wheels, fitted luggage set, and factory delivery sheets to Frankfurt.",
      category_id: "cat_automotive",
      image_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80",
      starting_price: 890000,
      min_increment: 30000,
      current_highest_bid: 1070000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 8,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -40,
      duration_mins: 180,
    },
    {
      id: "auc_live_porsche_carrera_rs",
      host_id: "usr_host_vikram",
      title: "1973 Porsche 911 Carrera RS 2.7 Lightweight (M471 Specification)",
      description: "Grand Prix White with Viper Green side script and matching Fuchs wheels. Weighs under 975 kg with thin-gauge sheet metal and Glaverbel lightweight glass.",
      category_id: "cat_automotive",
      image_url: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80",
      starting_price: 620000,
      min_increment: 20000,
      current_highest_bid: 740000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 7,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -60,
      duration_mins: 210,
    },
    {
      id: "auc_live_ferrari_275gtb",
      host_id: "usr_host_ananya",
      title: "1967 Ferrari 275 GTB/4 Berlinetta by Scaglietti (Rosso Corsa)",
      description: "Four-cam 3.3-liter Tipo 226 V12 producing 300 hp with six dual-choke Weber carburetors. Classiche certified with Red Book and continuous history.",
      category_id: "cat_automotive",
      image_url: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200&q=80",
      starting_price: 950000,
      min_increment: 35000,
      current_highest_bid: 1160000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 6,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -20,
      duration_mins: 300,
    },
    {
      id: "auc_live_mclaren_f1",
      host_id: "usr_host_vikram",
      title: "1994 McLaren F1 Three-Seater Supercar Production Chassis Tribute",
      description: "Center-seat carbon-fiber monocoque tribute engineered with naturally aspirated BMW Motorsport V12 and gold-foil lined engine bay heat shields.",
      category_id: "cat_automotive",
      image_url: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=80",
      starting_price: 1200000,
      min_increment: 50000,
      current_highest_bid: 1450000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 5,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -30,
      duration_mins: 190,
    }
  );

  // Vintage Cameras & Optics (4 Live)
  auctions.push(
    {
      id: "auc_live_leica_luxus",
      host_id: "usr_host_ananya",
      title: "1930 Leica I Model C Luxus Gold-Plated with Lizard Skin Covering",
      description: "One of only 95 Luxus factory cameras produced in Wetzlar. Features 50mm Elmar f/3.5 collapsible lens with matching gold trim and velvet presentation case.",
      category_id: "cat_cameras",
      image_url: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
      starting_price: 115000,
      min_increment: 4000,
      current_highest_bid: 139000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 7,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -90,
      duration_mins: 105, // Ends in 15m
    },
    {
      id: "auc_live_nikon_nasa",
      host_id: "usr_host_vikram",
      title: "1971 Nikon Photomic FTN NASA Apollo Command Module Flight Spec",
      description: "Finished in non-reflective matte grey with safety wire lugs, oversized knurled dials for EVA pressurized gloves, and NASA inspection stamps.",
      category_id: "cat_cameras",
      image_url: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=1200&q=80",
      starting_price: 85000,
      min_increment: 3000,
      current_highest_bid: 103000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 6,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -50,
      duration_mins: 160,
    },
    {
      id: "auc_live_hasselblad_500el",
      host_id: "usr_host_ananya",
      title: "Hasselblad 500EL Electric Motor Lunar Surface Duplicate Specimen",
      description: "Equipped with Zeiss Biogon 60mm f/5.6 lens and reseau grid glass plate for photogrammetric lunar topographic mapping. Provenance: Goteborg factory technician.",
      category_id: "cat_cameras",
      image_url: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=1200&q=80",
      starting_price: 92000,
      min_increment: 3500,
      current_highest_bid: 113000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 5,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -20,
      duration_mins: 140,
    },
    {
      id: "auc_live_rolleiflex_28f",
      host_id: "usr_host_vikram",
      title: "1960 Franke & Heidecke Rolleiflex 2.8F White Face TLR with Planar 80mm",
      description: "Dual-lens reflex medium format with Carl Zeiss 80mm f/2.8 Planar taking lens, coupled selenium light meter, and original bayonet hood and filters.",
      category_id: "cat_cameras",
      image_url: "https://images.unsplash.com/photo-1495707902641-75cac588d2e9?auto=format&fit=crop&w=1200&q=80",
      starting_price: 32000,
      min_increment: 1000,
      current_highest_bid: 39000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 4,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -40,
      duration_mins: 220,
    }
  );

  // Rare Books & Historical Manuscripts (4 Live)
  auctions.push(
    {
      id: "auc_live_newton_principia",
      host_id: "usr_host_ananya",
      title: "1687 Sir Isaac Newton 'Philosophiæ Naturalis Principia Mathematica' 1st Edition",
      description: "The two-line imprint first issue published in London by Samuel Pepys for the Royal Society. Bound in contemporary calf with geometric woodcut diagrams of universal gravitation.",
      category_id: "cat_books",
      image_url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80",
      starting_price: 650000,
      min_increment: 20000,
      current_highest_bid: 770000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 8,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -75,
      duration_mins: 95, // Ends in 20m
    },
    {
      id: "auc_live_shakespeare_folio",
      host_id: "usr_host_vikram",
      title: "1623 William Shakespeare First Folio Original Leaf from 'The Tempest'",
      description: "Framed single leaf (Act I, Scene II) with Droeshout typographical flourishes and watermarked rag paper. Certified authentic by the Folger Shakespeare Library.",
      category_id: "cat_books",
      image_url: "https://images.unsplash.com/photo-1463320726281-696a485928c7?auto=format&fit=crop&w=1200&q=80",
      starting_price: 75000,
      min_increment: 2500,
      current_highest_bid: 90000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 5,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -30,
      duration_mins: 150,
    },
    {
      id: "auc_live_darwin_origin",
      host_id: "usr_host_ananya",
      title: "1859 Charles Darwin 'On the Origin of Species' First Edition First Issue",
      description: "First edition with 32-page publisher's catalogue dated June 1859 and the folding diagram of phylogenetic speciation. Original green cloth binding by Edmonds & Remnants.",
      category_id: "cat_books",
      image_url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80",
      starting_price: 420000,
      min_increment: 15000,
      current_highest_bid: 495000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 6,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -45,
      duration_mins: 180,
    },
    {
      id: "auc_live_tolkien_hobbit",
      host_id: "usr_host_vikram",
      title: "1937 J.R.R. Tolkien 'The Hobbit' First Impression with Dustjacket",
      description: "One of 1,500 copies printed by George Allen & Unwin with author's uncorrected 'Dodgeson' flap typo and 10 monochrome illustrations by Tolkien.",
      category_id: "cat_books",
      image_url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=80",
      starting_price: 280000,
      min_increment: 10000,
      current_highest_bid: 330000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 7,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -15,
      duration_mins: 240,
    }
  );

  // Antique Jewelry & Rare Gems (4 Live)
  auctions.push(
    {
      id: "auc_live_golconda_diamond",
      host_id: "usr_host_ananya",
      title: "Golconda Mine 14.2 Carat Type IIa Uncut Flawless Diamond Talisman",
      description: "Historic ancient riverbed discovery exhibiting exceptional limpid optical transparency, absence of nitrogen impurities, and certified GIA Type IIa Golconda heritage.",
      category_id: "cat_jewelry",
      image_url: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=80",
      starting_price: 550000,
      min_increment: 20000,
      current_highest_bid: 670000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 9,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -105,
      duration_mins: 130, // Ends in 25m
    },
    {
      id: "auc_live_nizam_sarpech",
      host_id: "usr_host_vikram",
      title: "Nizam of Hyderabad 18th Century Emerald & Spinel Royal Sarpech Turban Ornament",
      description: "Articulated royal kalgi turban ornament set with Colombian octagonal-step cut emeralds (45 ct total), rose-cut diamonds, and hanging basra pearls.",
      category_id: "cat_jewelry",
      image_url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=80",
      starting_price: 480000,
      min_increment: 15000,
      current_highest_bid: 570000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 6,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -60,
      duration_mins: 200,
    },
    {
      id: "auc_live_cartier_tuttifrutti",
      host_id: "usr_host_ananya",
      title: "Art Deco 1925 Cartier 'Tutti Frutti' Carved Ruby & Emerald Platinum Bracelet",
      description: "Signature Jacques Cartier high-jewelry design featuring Moghul-style carved emerald leaves, fluted ruby berries, sapphire blossoms, and pavé diamonds. French assay marks.",
      category_id: "cat_jewelry",
      image_url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=80",
      starting_price: 390000,
      min_increment: 12000,
      current_highest_bid: 462000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 8,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -35,
      duration_mins: 170,
    },
    {
      id: "auc_live_burmese_ruby",
      host_id: "usr_host_vikram",
      title: "Mogok Valley 8.5 Carat Unheated 'Pigeon's Blood' Burmese Ruby Solitaire",
      description: "Certified SSEF and Gübelin gemological reports confirming natural unheated provenance from Myanmar with fiery crimson fluorescence and cushion brilliant cut.",
      category_id: "cat_jewelry",
      image_url: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1200&q=80",
      starting_price: 440000,
      min_increment: 15000,
      current_highest_bid: 515000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 5,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -10,
      duration_mins: 260,
    }
  );

  // Sculptures & Ancient Relics (4 Live)
  auctions.push(
    {
      id: "auc_live_chola_nataraja",
      host_id: "usr_host_ananya",
      title: "11th Century Chola Dynasty Lost-Wax Bronze Nataraja Shiva",
      description: "Magnificent divine cosmic dancer encircled by prabha-mandala ring of flames. Acquired in 1952 with registered Archaeological Survey of India (ASI) clearance certificate.",
      category_id: "cat_sculptures",
      image_url: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80",
      starting_price: 420000,
      min_increment: 15000,
      current_highest_bid: 495000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 7,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -85,
      duration_mins: 110, // Ends in 25m
    },
    {
      id: "auc_live_indus_seal",
      host_id: "usr_host_vikram",
      title: "Indus Valley Civilization Harappan Unicorn Steatite Seal Duplicate",
      description: "Certified archival cast replica from Mohenjo-Daro seal #DK-1927 exhibiting pictographic script and ceremonial feeding trough. Includes ASI reference documentation.",
      category_id: "cat_sculptures",
      image_url: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=1200&q=80",
      starting_price: 22000,
      min_increment: 1000,
      current_highest_bid: 28000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 5,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -30,
      duration_mins: 140,
    },
    {
      id: "auc_live_roman_bust",
      host_id: "usr_host_ananya",
      title: "2nd Century Roman Imperial Marble Bust of Emperor Marcus Aurelius",
      description: "Carved from fine crystalline Thassian marble depicting the Stoic philosopher-emperor with curled beard and paludamentum cloak. Provenance: Villa Torlonia, Rome.",
      category_id: "cat_sculptures",
      image_url: "https://images.unsplash.com/photo-1569429593410-b498b3fb3387?auto=format&fit=crop&w=1200&q=80",
      starting_price: 360000,
      min_increment: 12000,
      current_highest_bid: 432000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 6,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -50,
      duration_mins: 220,
    },
    {
      id: "auc_live_egyptian_scarab",
      host_id: "usr_host_vikram",
      title: "New Kingdom 18th Dynasty Lapis Lazuli Heart Scarab with Gold Mount",
      description: "Carved from deep ultramarine Afghan lapis lazuli inscribed with Chapter 30B of the Egyptian Book of the Dead for the royal scribe Amenhotep.",
      category_id: "cat_sculptures",
      image_url: "https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=1200&q=80",
      starting_price: 135000,
      min_increment: 5000,
      current_highest_bid: 160000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 4,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -15,
      duration_mins: 180,
    }
  );

  // Space, Cinema & Sports Memorabilia (7 Live)
  auctions.push(
    {
      id: "auc_live_apollo11_chart",
      host_id: "usr_host_ananya",
      title: "Apollo 11 Command Module Lunar Orbit Navigation Chart Signed by Michael Collins",
      description: "Flown photographic lunar map of Sea of Tranquility landing site #2 inscribed in pencil: 'Our orbital vantage point while Neil and Buzz walked - Michael Collins CMP'.",
      category_id: "cat_memorabilia",
      image_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
      starting_price: 95000,
      min_increment: 3000,
      current_highest_bid: 116000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 8,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -115,
      duration_mins: 125, // Ends in 10m
    },
    {
      id: "auc_live_jordan_jersey",
      host_id: "usr_host_vikram",
      title: "1998 Michael Jordan NBA Finals 'Last Dance' Game 2 Chicago Bulls Jersey",
      description: "Official red away jersey with black pinstripes worn during the 1998 championship run against the Utah Jazz. MeiGray Group photo-matched authentication.",
      category_id: "cat_memorabilia",
      image_url: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80",
      starting_price: 275000,
      min_increment: 10000,
      current_highest_bid: 335000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 7,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -40,
      duration_mins: 160,
    },
    {
      id: "auc_live_lightsaber_prop",
      host_id: "usr_host_ananya",
      title: "1977 Star Wars: A New Hope Original Luke Skywalker Graflex Lightsaber Hilt",
      description: "Screen-used prop constructed from a modified 1940s Graflex 3-cell flashgun with Kobold D-ring and T-track rubber grips. Certificate from Elstree Studios archive.",
      category_id: "cat_memorabilia",
      image_url: "https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?auto=format&fit=crop&w=1200&q=80",
      starting_price: 350000,
      min_increment: 12000,
      current_highest_bid: 422000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 9,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -70,
      duration_mins: 190,
    },
    {
      id: "auc_live_senna_helmet",
      host_id: "usr_host_vikram",
      title: "1991 Ayrton Senna Bell Formula 1 Race-Worn World Championship Helmet",
      description: "Painted by Sid Mosca in iconic yellow, green, and blue national Brazilian livery. Worn at Interlagos during his emotional first Brazilian Grand Prix victory.",
      category_id: "cat_memorabilia",
      image_url: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80",
      starting_price: 210000,
      min_increment: 8000,
      current_highest_bid: 258000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 6,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -25,
      duration_mins: 220,
    },
    {
      id: "auc_live_pele_jersey",
      host_id: "usr_host_ananya",
      title: "1970 FIFA World Cup Pelé Brazil Final Match Match-Worn #10 Jersey",
      description: "Canary yellow cotton jersey worn during the 4-1 victory over Italy in Mexico City. Inscribed in black ink by O Rei with photo-matching documentation.",
      category_id: "cat_memorabilia",
      image_url: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=80",
      starting_price: 185000,
      min_increment: 6000,
      current_highest_bid: 221000,
      highest_bidder_id: "usr_buyer_arjun",
      total_bids_count: 5,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -35,
      duration_mins: 260,
    },
    {
      id: "auc_live_bradman_bat",
      host_id: "usr_host_vikram",
      title: "1948 Sir Donald Bradman 'The Invincibles' Tour Match-Used Sykes Cricket Bat",
      description: "Original William Sykes & Sons willow bat signed across the face by the entire Australian touring squad during the historic undefeated English Ashes tour.",
      category_id: "cat_memorabilia",
      image_url: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=1200&q=80",
      starting_price: 130000,
      min_increment: 5000,
      current_highest_bid: 155000,
      highest_bidder_id: "usr_buyer_rahul",
      total_bids_count: 6,
      unique_bidders_count: 2,
      status: "LIVE",
      subscription_fee: 499,
      is_subscription_paid: true,
      start_offset_mins: -60,
      duration_mins: 150,
    },
    {
      id: "auc_live_beatles_autograph",
      host_id: "usr_host_ananya",
      title: "1964 The Beatles Fully-Signed 'A Hard Day's Night' UK Mono Album Sleeve",
      description: "Crisp vintage blue fountain pen signatures of John Lennon, Paul McCartney, George Harrison, and Ringo Starr on the reverse of the Parlophone LP jacket.",
      category_id: "cat_memorabilia",
      image_url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80",
      starting_price: 95000,
      min_increment: 3500,
      current_highest_bid: 116000,
      highest_bidder_id: "usr_buyer_priya",
      total_bids_count: 7,
      unique_bidders_count: 3,
      status: "LIVE",
      subscription_fee: 199,
      is_subscription_paid: true,
      start_offset_mins: -15,
      duration_mins: 180,
    }
  );

  // ============================================================================
  // 2. 22 UPCOMING AUCTIONS (Scheduled to Start in the Future)
  // ============================================================================

  const upcomingTemplates = [
    {
      title: "Original 1983 Apple Macintosh Prototype Engineering Unit #M0001",
      category: "cat_tech",
      price: 120000,
      inc: 5000,
      startMins: 30,
      dur: 240,
      img: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=1200&q=80",
      desc: "Pre-production engineering motherboard with Twiggy 5.25 inch drive bay and signatures of the original Mac team molded into inner casing. Museum grade provenance.",
    },
    {
      title: "1957 Omega Speedmaster Ref. CK 2915-1 'Broad Arrow' Chronograph",
      category: "cat_watches",
      price: 175000,
      inc: 6000,
      startMins: 60,
      dur: 300,
      img: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1200&q=80",
      desc: "The holy grail of Speedmasters: first generation with straight lugs, stainless steel engraved tachymetre bezel, broad arrow handset, and manual caliber 321.",
    },
    {
      title: "1962 Ferrari 250 GTO 1:8 Scale Master Blueprint Architectural Model",
      category: "cat_automotive",
      price: 45000,
      inc: 2000,
      startMins: 90,
      dur: 180,
      img: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200&q=80",
      desc: "Hand-machined aluminum spaceframe and dry-sump Colombo V12 recreation constructed from original Maranello factory chassis engineering drawings.",
    },
    {
      title: "Ancient Gandhara 3rd Century Schist Carved Bodhisattva Maitreya Statue",
      category: "cat_sculptures",
      price: 260000,
      inc: 10000,
      startMins: 120,
      dur: 360,
      img: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80",
      desc: "Greco-Buddhist sculpture exhibiting flowing Roman drapery, topknot ushnisha, and serene introspective expression. Verified export permit 1968.",
    },
    {
      title: "1912 Titanic White Star Line First-Class Silver-Plated Table Service Set",
      category: "cat_collectibles",
      price: 55000,
      inc: 2500,
      startMins: 180,
      dur: 240,
      img: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=1200&q=80",
      desc: "Manufactured by Elkington & Co. with embossed burgee emblem of White Star Line. Retrieved from Southampton warehouse inventory.",
    },
    {
      title: "1610 Galileo Galilei 'Sidereus Nuncius' Illustrated Starry Messenger Leaf",
      category: "cat_books",
      price: 190000,
      inc: 8000,
      startMins: 240,
      dur: 400,
      img: "https://images.unsplash.com/photo-1507842229452-972f10b64d12?auto=format&fit=crop&w=1200&q=80",
      desc: "Features Galileo's landmark woodcut illustrations of the craters of the Moon and the four Galilean moons of Jupiter observed through his handmade telescope.",
    },
    {
      title: "1972 Leica M4 Black Paint Wetzlar Rangefinder with 35mm Summicron",
      category: "cat_cameras",
      price: 68000,
      inc: 2500,
      startMins: 300,
      dur: 320,
      img: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
      desc: "Original factory black enamel finish with subtle natural brassing on top plate edges. Paired with 8-element 35mm f/2 Summicron lens and Leicavit MP winder.",
    },
    {
      title: "Kashmir Sapphire 6.4 Carat Royal Blue Untreated Velvet Gemstone",
      category: "cat_jewelry",
      price: 340000,
      inc: 12000,
      startMins: 360,
      dur: 420,
      img: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=80",
      desc: "Historical old-mine Zanskar valley origin exhibiting the signature velvety optical texture caused by ultra-fine rutile silk without thermal enhancement.",
    },
    {
      title: "Jamini Roy 1945 Tempera on Woven Mat 'Gopini with Sacred Pitcher'",
      category: "cat_art",
      price: 95000,
      inc: 4000,
      startMins: 420,
      dur: 300,
      img: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
      desc: "Kalighat folk art movement masterpiece utilizing organic mineral and vegetal pigments on hand-woven Bengal palm matting. National heritage registration.",
    },
    {
      title: "1969 Apollo 12 Flown Lunar Surface Beta Cloth Mission Patch",
      category: "cat_memorabilia",
      price: 42000,
      inc: 1500,
      startMins: 480,
      dur: 280,
      img: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80",
      desc: "Fireproof beta cloth mission insignia certified as carried to the Ocean of Storms by lunar module pilot Alan Bean with hand-written verification.",
    },
    {
      title: "F.P. Journe Chronomètre Bleu Tantalum Case with Mirror Blue Dial",
      category: "cat_watches",
      price: 165000,
      inc: 5000,
      startMins: 540,
      dur: 360,
      img: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80",
      desc: "39mm rare tantalum metal case with 18k rose gold manufacture movement caliber 1304 and chrome-like blue lacquered dial that shifts under light.",
    },
    {
      title: "1989 Nintendo World Championships Gold Cartridge Engineering Sample",
      category: "cat_tech",
      price: 85000,
      inc: 3000,
      startMins: 600,
      dur: 300,
      img: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
      desc: "One of only 26 triangular DIP switch gold test cartridges issued by Nintendo Power magazine. Guaranteed fully operational with Super Mario, Rad Racer, and Tetris.",
    },
    {
      title: "1954 Jaguar D-Type Le Mans 24-Hour Tribute Long-Nose Fin Monocoque",
      category: "cat_automotive",
      price: 480000,
      inc: 15000,
      startMins: 660,
      dur: 400,
      img: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
      desc: "Aircraft-grade tubular chassis with aerodynamic stabilizing tail fin and dry-sump 3.4L XK twin-cam engine fitted with triple Weber 45 DCO3 carburetors.",
    },
    {
      title: "18th Century Jaipur Enamel Minakari Gold & Emerald Elephant Figurine",
      category: "cat_sculptures",
      price: 110000,
      inc: 4000,
      startMins: 720,
      dur: 320,
      img: "https://images.unsplash.com/photo-1569429593410-b498b3fb3387?auto=format&fit=crop&w=1200&q=80",
      desc: "Hand-painted polychrome minakari champlevé enamel on solid 22k gold armature, adorned with table-cut diamonds and royal ceremonial howdah.",
    },
    {
      title: "1922 US Saint-Gaudens Double Eagle $20 Gold Coin MS-66",
      category: "cat_collectibles",
      price: 52000,
      inc: 2000,
      startMins: 780,
      dur: 280,
      img: "https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&w=1200&q=80",
      desc: "Augustus Saint-Gaudens masterpiece featuring Lady Liberty striding before sun rays on obverse and flying eagle reverse. Certified PCGS MS-66.",
    },
    {
      title: "1818 Mary Shelley 'Frankenstein; or, The Modern Prometheus' 1st Edition",
      category: "cat_books",
      price: 320000,
      inc: 12000,
      startMins: 840,
      dur: 480,
      img: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80",
      desc: "Extremely scarce anonymous three-volume first edition printed in London by Lackington, Hughes, Harding, Mavor, & Jones. Retains original half-titles.",
    },
    {
      title: "1948 Alpa Reflex Model III 35mm SLR with Kern-Macro Switar 50mm",
      category: "cat_cameras",
      price: 29000,
      inc: 1000,
      startMins: 900,
      dur: 260,
      img: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=1200&q=80",
      desc: "Handcrafted Swiss precision camera by Pignons S.A. featuring unique 45-degree angle reflex viewfinder and legendary Apochromatic Kern-Switar optics.",
    },
    {
      title: "Natural Saltwater Basra Pearl 7-Strand Satlada Royal Necklace",
      category: "cat_jewelry",
      price: 280000,
      inc: 10000,
      startMins: 960,
      dur: 420,
      img: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=80",
      desc: "Seven graduating strands comprising 465 matched natural basra pearls from the Persian Gulf, united by diamond and Burmese ruby floral side clasps.",
    },
    {
      title: "Tyeb Mehta 1982 Diagonal Series Oil on Canvas Study",
      category: "cat_art",
      price: 380000,
      inc: 15000,
      startMins: 1020,
      dur: 500,
      img: "https://images.unsplash.com/photo-1578925518470-4def7a0f08bb?auto=format&fit=crop&w=1200&q=80",
      desc: "Signature lightning diagonal division fracturing the tragic human silhouette into dual psychological planes. Exhibited at Chemould Prescott Road.",
    },
    {
      title: "1994 Ayrton Senna Final San Marino Grand Prix Signed Steering Wheel",
      category: "cat_memorabilia",
      price: 175000,
      inc: 7000,
      startMins: 1080,
      dur: 360,
      img: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80",
      desc: "Personal MOMO suede racing steering wheel signed in silver paint pen during testing at Imola. Accompanied by team engineer notarized declaration.",
    },
    {
      title: "1960 Rolex Submariner Ref. 5512 'Meters First' 4-Line Chronometer",
      category: "cat_watches",
      price: 145000,
      inc: 5000,
      startMins: 1140,
      dur: 300,
      img: "https://images.unsplash.com/photo-1547996160-71dfabb1a7cf?auto=format&fit=crop&w=1200&q=80",
      desc: "Gilt gloss dial with chapter ring, pointed crown guards (PCG), faded charcoal 'ghost' bezel insert, and riveted Swiss Oyster bracelet.",
    },
    {
      title: "1981 Osborne 1 First Commercial Portable Computer Signed by Lee Felsenstein",
      category: "cat_tech",
      price: 24000,
      inc: 1000,
      startMins: 1200,
      dur: 240,
      img: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
      desc: "Complete working system with built-in 5-inch monochrome CRT display, dual 5.25 floppy drives, detachable keyboard, and complete CP/M software suite.",
    },
  ];

  upcomingTemplates.forEach((item, idx) => {
    auctions.push({
      id: `auc_upc_${idx + 1}`,
      host_id: hosts[idx % hosts.length],
      title: item.title,
      description: item.desc,
      category_id: item.category,
      image_url: item.img,
      starting_price: item.price,
      min_increment: item.inc,
      current_highest_bid: item.price,
      highest_bidder_id: null,
      total_bids_count: 0,
      unique_bidders_count: 0,
      status: "UPCOMING",
      subscription_fee: item.price > 100000 ? 499 : 199,
      is_subscription_paid: true,
      start_offset_mins: item.startMins,
      duration_mins: item.dur,
    });
  });

  // ============================================================================
  // 3. 32 COMPLETED / HISTORICAL ARCHIVE AUCTIONS (Historic Artifacts & Sales)
  // ============================================================================

  const historicalArtifacts = [
    {
      title: "1965 Shelby Cobra 427 S/C Competition Spec Die-Cast Archive Model",
      category: "cat_collectibles",
      price: 8000,
      inc: 500,
      soldFor: 14500,
      winner: "usr_buyer_priya",
      bidsCount: 8,
      endedMinsAgo: 120,
      img: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200&q=80",
      desc: "Hand-assembled 1:1 scale tribute model with authentic Carroll Shelby autograph on aluminum firewall. Concluded successfully.",
    },
    {
      title: "1976 Apple-1 Computer Motherboard Signed by Steve Wozniak",
      category: "cat_tech",
      price: 250000,
      inc: 10000,
      soldFor: 385000,
      winner: "usr_buyer_rahul",
      bidsCount: 16,
      endedMinsAgo: 360,
      img: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
      desc: "Fully operational original Apple-1 motherboard #01-0068 with MOS Technology 6502 microprocessor and period Datanetics ASCII keyboard. Historic computing artifact.",
    },
    {
      title: "1913 US Liberty Head Nickel Famous Five Replica Strike",
      category: "cat_collectibles",
      price: 35000,
      inc: 1500,
      soldFor: 58000,
      winner: "usr_buyer_arjun",
      bidsCount: 12,
      endedMinsAgo: 720,
      img: "https://images.unsplash.com/photo-1541480601022-2308c0f02487?auto=format&fit=crop&w=1200&q=80",
      desc: "Exact weight reproduction of the unauthorized midnight strike from the Philadelphia Mint. Museum provenance verified.",
    },
    {
      title: "1957 Omega Speedmaster CK2915-1 'Broad Arrow' 1st Generation",
      category: "cat_watches",
      price: 180000,
      inc: 6000,
      soldFor: 275000,
      winner: "usr_buyer_arjun",
      bidsCount: 14,
      endedMinsAgo: 1440,
      img: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80",
      desc: "First generation Speedmaster with matching radium luminescence on broad arrow hands and steel Base 1000 bezel.",
    },
    {
      title: "1961 Yuri Gagarin Vostok-1 Mission Signed Space Recovery Log",
      category: "cat_memorabilia",
      price: 120000,
      inc: 5000,
      soldFor: 195000,
      winner: "usr_buyer_rahul",
      bidsCount: 15,
      endedMinsAgo: 2160,
      img: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
      desc: "First human spaceflight landing field log signed by Cosmonaut Yuri Gagarin minutes after capsule touchdown in Saratov Oblast.",
    },
    {
      title: "1952 Topps Mickey Mantle #311 Baseball Card PSA-8 Near Mint",
      category: "cat_collectibles",
      price: 300000,
      inc: 10000,
      soldFor: 440000,
      winner: "usr_buyer_priya",
      bidsCount: 18,
      endedMinsAgo: 2880,
      img: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80",
      desc: "The holy grail of post-war sports cards with vibrant cyan borders, impeccable centering, and sharp corners.",
    },
    {
      title: "1886 Benz Patent-Motorwagen Full Working Scale Replica",
      category: "cat_automotive",
      price: 65000,
      inc: 2500,
      soldFor: 92000,
      winner: "usr_buyer_arjun",
      bidsCount: 11,
      endedMinsAgo: 3600,
      img: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
      desc: "Accurately constructed 1:1 functional reproduction of Carl Benz's three-wheeled petrol vehicle with horizontal flywheel.",
    },
    {
      title: "1923 Leica Null-Serie 0-Series Prototype Replica Wetzlar 1970",
      category: "cat_cameras",
      price: 48000,
      inc: 2000,
      soldFor: 71000,
      winner: "usr_buyer_rahul",
      bidsCount: 9,
      endedMinsAgo: 4320,
      img: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
      desc: "Precision mechanical recreation of Oskar Barnack's legendary 35mm pocket camera prototype.",
    },
    {
      title: "1890 Vincent van Gogh Hand-Annotated Letter to Brother Theo",
      category: "cat_books",
      price: 450000,
      inc: 15000,
      soldFor: 620000,
      winner: "usr_buyer_priya",
      bidsCount: 22,
      endedMinsAgo: 5040,
      img: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
      desc: "Two-page French letter penned in Auvers-sur-Oise containing pen sketches of cypresses and philosophical reflections.",
    },
    {
      title: "16th Century Persian Safavid Silk & Gold-Thread Hunting Carpet",
      category: "cat_art",
      price: 280000,
      inc: 10000,
      soldFor: 395000,
      winner: "usr_buyer_arjun",
      bidsCount: 13,
      endedMinsAgo: 5760,
      img: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80",
      desc: "Isfahan royal atelier fragment woven with natural cochineal dye, depicting equestrian hunters pursuing gazelles.",
    },
    {
      title: "1982 Commodore 64 Serial #000001 Engineering Verification Board",
      category: "cat_tech",
      price: 32000,
      inc: 1000,
      soldFor: 49000,
      winner: "usr_buyer_rahul",
      bidsCount: 10,
      endedMinsAgo: 6480,
      img: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
      desc: "First functional prototype PCB populated with ceramic SID 6581 sound synthesizer chip and VIC-II graphics processor.",
    },
    {
      title: "1963 Rolex Cosmograph Daytona Ref. 6239 'Double Swiss' Underline",
      category: "cat_watches",
      price: 210000,
      inc: 8000,
      soldFor: 315000,
      winner: "usr_buyer_arjun",
      bidsCount: 15,
      endedMinsAgo: 7200,
      img: "https://images.unsplash.com/photo-1547996160-71dfabb1a7cf?auto=format&fit=crop&w=1200&q=80",
      desc: "Extremely rare transitional Daytona with underline mark above 6 o'clock and double Swiss signature at bottom dial.",
    },
    {
      title: "1856 British Guiana 1-Cent Black on Magenta Reproduction Archival Ingot",
      category: "cat_collectibles",
      price: 40000,
      inc: 1500,
      soldFor: 62000,
      winner: "usr_buyer_priya",
      bidsCount: 11,
      endedMinsAgo: 7920,
      img: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1200&q=80",
      desc: "Museum recreation of the world's most valuable postage stamp with postmaster initial 'EDW'.",
    },
    {
      title: "1936 Bugatti Type 57SC Atlantic Aerolithe Concept Scale Model",
      category: "cat_automotive",
      price: 55000,
      inc: 2000,
      soldFor: 83000,
      winner: "usr_buyer_rahul",
      bidsCount: 12,
      endedMinsAgo: 8640,
      img: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80",
      desc: "Riveted magnesium alloy body model representing Jean Bugatti's lost magnesium concept car.",
    },
    {
      title: "1959 Nikon F NASA Orbital Test Model Serial #6400002",
      category: "cat_cameras",
      price: 75000,
      inc: 3000,
      soldFor: 118000,
      winner: "usr_buyer_arjun",
      bidsCount: 14,
      endedMinsAgo: 9360,
      img: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=1200&q=80",
      desc: "First SLR modified for Gemini space orbital vacuum testing with specialized non-degassing dry lubricants.",
    },
    {
      title: "1543 Nicolaus Copernicus 'De revolutionibus orbium coelestium' 1st Edition Leaf",
      category: "cat_books",
      price: 180000,
      inc: 6000,
      soldFor: 265000,
      winner: "usr_buyer_priya",
      bidsCount: 16,
      endedMinsAgo: 10080,
      img: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80",
      desc: "Historic astronomical diagram leaf presenting the heliocentric solar system model published in Nuremberg.",
    },
    {
      title: "4th Century BCE Hellenistic Gold Filigree Laurel Wreath Diadem",
      category: "cat_jewelry",
      price: 320000,
      inc: 12000,
      soldFor: 460000,
      winner: "usr_buyer_arjun",
      bidsCount: 17,
      endedMinsAgo: 10800,
      img: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=80",
      desc: "Ancient Macedonian royal burial diadem featuring delicate hammered gold olive leaves and natural garnet cabochons.",
    },
    {
      title: "10th Century Khmer Empire Angkor Wat Sandstone Apsara Relief",
      category: "cat_sculptures",
      price: 290000,
      inc: 10000,
      soldFor: 410000,
      winner: "usr_buyer_rahul",
      bidsCount: 13,
      endedMinsAgo: 11520,
      img: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80",
      desc: "Carved pink sandstone celestial dancer exhibiting elaborate lotus crown and sampot headdress.",
    },
    {
      title: "1969 Neil Armstrong Apollo 11 Lunar Module Descent Checklist Page",
      category: "cat_memorabilia",
      price: 210000,
      inc: 8000,
      soldFor: 310000,
      winner: "usr_buyer_priya",
      bidsCount: 15,
      endedMinsAgo: 12240,
      img: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
      desc: "Surface-flown checklist with cockpit handwritten notations: 'Pitchover complete, 3000 feet, P64'.",
    },
    {
      title: "1970 Patek Philippe Nautilus Ref. 3700/1A 'Jumbo' Gérald Genta Design",
      category: "cat_watches",
      price: 140000,
      inc: 5000,
      soldFor: 205000,
      winner: "usr_buyer_rahul",
      bidsCount: 14,
      endedMinsAgo: 12960,
      img: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1200&q=80",
      desc: "First series Nautilus in stainless steel with ribbed blue-black dial and ultra-thin caliber 28-255 C movement.",
    },
    {
      title: "1804 US Draped Bust Silver Dollar Class I Restrike Archive Proof",
      category: "cat_collectibles",
      price: 45000,
      inc: 2000,
      soldFor: 74000,
      winner: "usr_buyer_arjun",
      bidsCount: 12,
      endedMinsAgo: 13680,
      img: "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=1200&q=80",
      desc: "Numismatic tribute to the 'King of American Coins' originally struck for diplomatic gift presentation to the King of Siam.",
    },
    {
      title: "1967 Toyota 2000GT Coupe (Chassis #MF10-10129) Right Hand Drive",
      category: "cat_automotive",
      price: 520000,
      inc: 18000,
      soldFor: 710000,
      winner: "usr_buyer_priya",
      bidsCount: 19,
      endedMinsAgo: 14400,
      img: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80",
      desc: "Japan's first genuine supercar with Yamaha twin-cam 2.0L inline-six, rosewood dashboard, and magnesium alloy wheels.",
    },
    {
      title: "1954 Leica M3 Double-Stroke Serial #700015 Early Production",
      category: "cat_cameras",
      price: 65000,
      inc: 2500,
      soldFor: 98000,
      winner: "usr_buyer_rahul",
      bidsCount: 13,
      endedMinsAgo: 15120,
      img: "https://images.unsplash.com/photo-1495707902641-75cac588d2e9?auto=format&fit=crop&w=1200&q=80",
      desc: "Corner-glass viewfinder version from the inaugural batch of 10,000 M3 bodies produced at Leitz Wetzlar.",
    },
    {
      title: "1637 René Descartes 'Discours de la méthode' First Edition",
      category: "cat_books",
      price: 240000,
      inc: 9000,
      soldFor: 350000,
      winner: "usr_buyer_arjun",
      bidsCount: 15,
      endedMinsAgo: 15840,
      img: "https://images.unsplash.com/photo-1463320726281-696a485928c7?auto=format&fit=crop&w=1200&q=80",
      desc: "Containing the foundational philosophical axiom 'Cogito, ergo sum' in pristine seventeenth-century vellum binding.",
    },
    {
      title: "Mughal Empire 17th Century Inscribed Spinach Green Jade Archer's Ring",
      category: "cat_jewelry",
      price: 38000,
      inc: 1500,
      soldFor: 59000,
      winner: "usr_buyer_priya",
      bidsCount: 11,
      endedMinsAgo: 16560,
      img: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=80",
      desc: "Thumb ring carved from nephrite jade inlaid with kundan gold floral scrollwork and rubies. Imperial workshop inscription.",
    },
    {
      title: "12th Century Romanesque French Limestone Capital Sculpture",
      category: "cat_sculptures",
      price: 160000,
      inc: 6000,
      soldFor: 235000,
      winner: "usr_buyer_rahul",
      bidsCount: 12,
      endedMinsAgo: 17280,
      img: "https://images.unsplash.com/photo-1569429593410-b498b3fb3387?auto=format&fit=crop&w=1200&q=80",
      desc: "Architectural column capital carved with acanthus leaves and mythical confronting griffins from an abbey in Burgundy.",
    },
    {
      title: "1977 Apple Computer 'Rainbow' Cassette Tape Basic 1.0 Original",
      category: "cat_tech",
      price: 18000,
      inc: 800,
      soldFor: 29500,
      winner: "usr_buyer_arjun",
      bidsCount: 10,
      endedMinsAgo: 18000,
      img: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80",
      desc: "Magnetic cassette tape for Apple II system loading integer basic, labeled in Steve Jobs' original typeface.",
    },
    {
      title: "1980 Muhammad Ali Signed 'Rumble in the Jungle' Everlast Gloves",
      category: "cat_memorabilia",
      price: 85000,
      inc: 3000,
      soldFor: 132000,
      winner: "usr_buyer_rahul",
      bidsCount: 14,
      endedMinsAgo: 18720,
      img: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80",
      desc: "Red leather 8oz sparring gloves inscribed 'To my friend, from Muhammad Ali 1980' with photo proof from Deer Lake camp.",
    },
    {
      title: "1969 Audemars Piguet Ultra-Thin Caliber 2003 Skeletonized Pocket Watch",
      category: "cat_watches",
      price: 95000,
      inc: 4000,
      soldFor: 142000,
      winner: "usr_buyer_priya",
      bidsCount: 13,
      endedMinsAgo: 19440,
      img: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80",
      desc: "1.64mm thick openworked movement hand-engraved with floral Arabesque patterns in 18k yellow gold case.",
    },
    {
      title: "1893 World's Columbian Exposition Chicago Gold Medal Proof",
      category: "cat_collectibles",
      price: 28000,
      inc: 1000,
      soldFor: 44000,
      winner: "usr_buyer_arjun",
      bidsCount: 11,
      endedMinsAgo: 20160,
      img: "https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&w=1200&q=80",
      desc: "Award medal designed by Augustus Saint-Gaudens and Charles E. Barber commemorating 400th anniversary of Columbus' voyage.",
    },
    {
      title: "1971 Lamborghini Miura SV (Spinto Veloce) Chassis #4884 Tribute Spec",
      category: "cat_automotive",
      price: 580000,
      inc: 20000,
      soldFor: 840000,
      winner: "usr_buyer_rahul",
      bidsCount: 20,
      endedMinsAgo: 20880,
      img: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=80",
      desc: "The pinnacle of the Miura lineage with split-sump lubrication for the transverse 385 hp 3.9L quad-cam V12 and wider rear fenders.",
    },
    {
      title: "1938 Zeiss Ikon Contax II with Carl Zeiss Jena 50mm f/1.5 Sonnar",
      category: "cat_cameras",
      price: 24000,
      inc: 1000,
      soldFor: 37500,
      winner: "usr_buyer_priya",
      bidsCount: 9,
      endedMinsAgo: 21600,
      img: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=1200&q=80",
      desc: "Pre-war Dresden rangefinder featuring all-metal vertical travel focal plane shutter and collapsible fast Sonnar glass.",
    }
  ];

  historicalArtifacts.forEach((item, idx) => {
    auctions.push({
      id: `auc_hist_${idx + 1}`,
      host_id: hosts[idx % hosts.length],
      title: item.title,
      description: item.desc,
      category_id: item.category,
      image_url: item.img,
      starting_price: item.price,
      min_increment: item.inc,
      current_highest_bid: item.soldFor,
      highest_bidder_id: item.winner,
      total_bids_count: item.bidsCount,
      unique_bidders_count: 3,
      status: "ENDED",
      subscription_fee: item.price > 100000 ? 499 : (item.price > 10000 ? 199 : 99),
      is_subscription_paid: true,
      winner_id: item.winner,
      winning_bid_amount: item.soldFor,
      settled_at_offset_mins: -item.endedMinsAgo,
      start_offset_mins: -(item.endedMinsAgo + 300),
      duration_mins: 300,
    });
  });

  return auctions;
}
